name: Dependency Management

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
    
    - name: Create requirements.in from current requirements.txt
      run: |
        # Create a base requirements.in file
        cat > requirements.in << 'EOF'
        # Core dependencies
        pyyaml>=6.0
        requests>=2.28.0
        jinja2>=3.1.0
        click>=8.0.0
        rich>=13.0.0
        tabulate>=0.9.0
        
        # Development dependencies
        pytest>=7.0.0
        black>=22.0.0
        flake8>=5.0.0
        mypy>=0.991
        EOF
    
    - name: Update dependencies
      run: |
        pip-compile --upgrade requirements.in
        
    - name: Test with updated dependencies
      run: |
        pip install -r requirements.txt
        python test_installation.py
        python review_architecture.py sample_architecture.md
    
    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check --json --output safety-report.json || echo "Security check completed with warnings"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated updates to project dependencies.
          
          ### Changes
          - Updated Python package versions to latest compatible versions
          - Ran security check with safety
          - Verified all tests still pass
          
          ### Review Checklist
          - [ ] All CI checks pass
          - [ ] No breaking changes in updated packages
          - [ ] Security scan results are acceptable
          
          **Note**: This PR was created automatically by the dependency management workflow.
        branch: chore/update-dependencies
        delete-branch: true
    
    - name: Upload security report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: dependency-security-report
        path: safety-report.json

  check-outdated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check for outdated packages
      run: |
        pip list --outdated --format=json > outdated-packages.json
        python -c "
        import json
        import sys
        
        with open('outdated-packages.json', 'r') as f:
            outdated = json.load(f)
        
        if outdated:
            print('📦 Outdated packages found:')
            for pkg in outdated:
                print(f\"  - {pkg['name']}: {pkg['version']} → {pkg['latest_version']}\")
            print()
            print('Consider running the dependency update workflow.')
        else:
            print('✅ All packages are up to date!')
        "
    
    - name: Upload outdated packages report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: outdated-packages-report
        path: outdated-packages.json
